### ISSUE TITLE
Unable to "wake" spotify connect speaker

### ISSUE THREAD

**Issue by Edddlund** [athombv/com.spotify#11]
I have Harman Kardon Omni 10 and 20+ with built-in Spotify Connect, I can control the speakers while they are in active mode, but I can not wake them up when they are inactive.

It should just be like Spotify App, that you choose the speaker to make it wake up.

// Edddlund

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2627
