### ISSUE TITLE
spotify reacts very slow (2-3 minutes!) in playing, pausing etc.

### ISSUE THREAD

**Issue by philsniff** [athombv/com.spotify#5]
works now (very buggy) with amazonn dot now! 
seems like spotify found the bug that didn't allowed the connection before.

but homey reacts very, very late (2-3 minutes) with playing and pausing etc.

but i hope the development now can go on again ;-)

**Comment by Wijkie76** [comment]
Using the private session mode, no autoplay and no fade between songs seems to help. Also i noticed it doesn't react well to special characters... once you search for a song containing special charactars the search backs-up and the next sond takes a while to load... perhaps a max loadingtime could be implemented? So if a song doesn't load within for ex. 20 secs, the app clears the search?

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2632
