### ISSUE TITLE
Cannot login into Spotify

### ISSUE THREAD

**Issue by raskiman** [athombv/com.spotify#8]
Hi, 

I can't login anymore into Spotify. Tried with the stable and beta (1.1.5) version. Restarted homey etc. Nothing works. 
I see the screen in the Settings with the Avatar and the "Log in " button, but nothing works. 

![image](https://user-images.githubusercontent.com/11738613/33523900-fb7853c4-d811-11e7-9256-4584b207fc28.png)

Can I find logs or something somewhere? 
Any ideas?

**Comment by BasKiers** [comment]
Hi,

Could you check if your browser blocks popups (a message should appear in the rightmost part of the address bar in chrome)? Since the "Log In" button should open a popup with the Spotify Login form.

Regards,
Bas

**Comment by raskiman** [comment]
Hey Bas,
I use the Homey app on Mac OSX..

**Comment by BasKiers** [comment]
Hi,

Could you check you are running v1.0.4 of the desktop app. You can see the app version by clicking "Homey" in the menu bar at the top left. If you are running the latest version could you click the "Log In" button in the Homey settings view of the Spotify app and check if the window is not opened in the background by right clicking the Homey icon in your taskbar like in the screenshot blow:

![image](https://user-images.githubusercontent.com/6036127/33882964-3c92efde-df3a-11e7-817f-b85fc14e5d60.png)

Regards,
Bas

**Comment by raskiman** [comment]
hey Bas, 
That worked! Thx!

Can the Homey update automatically in the future? That would avoid these issues..
