### ISSUE TITLE
Spotify Sonos doesn't work as expected (Having Left/Right channel speakers and Boost)

### ISSUE THREAD

**Issue by mveck** [athombv/com.spotify#9]
When attempting to play music using Spotify Connect (For Sonos), the music from Spotify cannot run. All nr's scroll (don't play). Only option I have is activating an existing Sonos stream (selected by Sonos app e.g. Intune).

Homey Core: 1.5.8

Spotify Connect version 2.0.1
Sonos 2.3.1

Sonos Config:
Boost 8.4
Play:1 8.4
Play:1 8.4 

Both play:1's are combined as left-right pair in a single group

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2629
